posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed

#This is class is a form which allows a post to be created by a user
class NewPost(FlaskForm):
    title = StringField('Title', validators= [DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

# This class is a form which allows comments to be posted under a post
class NewComment(FlaskForm):
	content = TextAreaField('Comment', validators=[DataRequired()])
	submit = SubmitField('Submit')

main/routes.py
from flask import (render_template, request, Blueprint, make_response,g,current_app,
redirect, url_for)
from flaskapp.models import Post,User
from flask_login import current_user, login_required
from datetime import datetime
from flaskapp import db
from flask import g
from flaskapp.main.forms import Searcher

main = Blueprint('main', __name__)


@main.route('/pastpapers')
def pastpaper():
    return render_template("pastpapers.html")

#This is the homepage subroutine. 
@main.route('/')
@main.route('/home')
def HomePage():
    page = request.args.get('page', 1, type = int)
    showed_followed = False
    if current_user.is_authenticated:
        showed_followed = bool(request.cookies.get('showed_followed', ''))
    if showed_followed:
        query= current_user.followed_posts
    else: 
        query = Post.query
    pagination = query.order_by(Post.date_posted.desc()).paginate(page = page, per_page = 5, 
            error_out = False)
    posts = pagination.items
    return render_template("HomePage.html", posts =posts, showed_followed = showed_followed , 
        pagination = pagination)

#This is where all the posts submitted by users are sent to . This is the post area
@main.route("/compscipost",methods=['GET', 'POST'])
def compscipost():
	page = request.args.get('page', 1, type = int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page, per_page = 5)
	return render_template("compscipost.html", posts = posts)

#Subroutine for about page
@main.route("/about")
def about():
    return render_template("About.html", title = 'About')

#Subroutine for contact page 
@main.route("/contact")
def contact():
    return render_template("contact.html", title = 'Contact Us')

#This subroutine shows 5 posts from post area to homepage.
@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('main.HomePage')))
    resp.set_cookie('showed_followed', '' , max_age = 30*24*60*60)
    return resp

#This subroutine shows 5 posts from post area to homepage.
@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('main.HomePage')))
    resp.set_cookie('showed_followed', '1', max_age = 30*24*60*60)
    return resp

#This is for the search function
@main.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = Searcher()

#This is the searh subroutine.
@main.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.HomePage'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=('Search'), posts=posts,
                           next_url=next_url, prev_url=prev_url)

posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, current_app
from flask_login import current_user, login_required
from flaskapp import db
from flaskapp.models import Post, Comment, User
from flaskapp.posts.forms import NewPost, NewComment

posts = Blueprint('posts', __name__)


#This subroutine creates a post. 
@posts.route("/post/new", methods = ['GET', 'POST'])
@login_required
def new_post():
    form = NewPost()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        #Adds Post To DataBase
        flash("Your Post has been posted!", 'success')
        return redirect(url_for('main.compscipost'))
    return render_template('create_post.html', title='New Post', form = form, 
        legend = "New Post ")

#This allows the post to be viewed .
@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = NewComment()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data,commenter_author= post,
            comment_author = current_user)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.')
        return redirect(url_for('posts.post', post_id=post.id, page=-1))
    page = request.args.get('page', 1, type = int)
    if page == -1:
        page = (post.comments.count() - 1) // \
            current_app.config['COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.date_posted.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('comments_post.html', post=post, form = form ,
        comments=comments, pagination = pagination)


#This subroutine allows for post to be liked .
@posts.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

#This subroutine allows the specific post of a user to be edited by the user 
@posts.route("/post/<int:post_id>/Edit", methods = ['GET', 'POST'])
@login_required
def edit_post(post_id): 
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) 
    form = NewPost()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id = post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data =post.content  
    return render_template('create_post.html', title='Edit Post', form = form,
        legend = "Edit Post")

#This subroutine allows the specific post of a user to be deleted by the user.

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.compscipost'))




users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,current_app, jsonify
from datetime import datetime
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db, bcrypt
from flaskapp.models import User, Post,Message,Notification
from flaskapp.users.forms import (SignUp, Login, UpdateAccount,
                                   RequestReset, ResetPassword, NewMessage) # this imports the classes from the python file 'forms.py' 
from flaskapp.users.util import save_pic, send_email

users = Blueprint('users', __name__) #This a blueprint which provides seperation at the Flask level . This seperates the whole folder called users from the application. This allows the sharing of application config, and can change an application object as necessary with being registered. 



@users.route("/signup", methods = ['GET','POST'] ) # This links the URL of the SignUp Page to this subroutine . The html methods being used are GET & POST
def signup():
    # If the current user is set , the user is automatically redirected to the user home page.
    if current_user.is_authenticated:
        return redirect(url_for('main.HomePage'))
    form = SignUp()#The form is set equal to the SignUp class in forms.py and undergoes the signup prcoess  
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf- 8') # This is Flask-Bcrypt (This is the hashing utility which applies a hash function on the password entered by the user. This turns the plain text password to a hash value)
        user = User(username = form.username.data, email = form.email.data, password = hashed_password) # The variable user is set equal to all the information inputted by the user such as Email,Password etc
        db.session.add(user) # The db.session.add() inserts the information enetred by the user into the database. Firstly it has to create the Python object which has been done above . Then it is added to the session.
        db.session.commit() # Lastly it has to be commited to the session in order to insert to the database
        flash('Your account has been created! You are now able to log in', 'success') # this prints a message telling the user that the account has been created successfully 
        return redirect(url_for('users.login')) # After the message has popped up the user will be redirected to the login page.
    return render_template('signup.html', title = 'Signup', form = form) # in order to render a HTML template the render_template() method has to be used. In order to render the template , the name of the template and the variables you want to pass to the template engine as keyword arguments have to be provided .
    # In this case template name 'signup.html' variables being passed- title = 'Signup', form = form



@users.route("/login", methods=['GET', 'POST']) # This links the URL of the login Page to this subroutine . The html methods being used are GET & POST
def login():
    # If the current user is logged in, the user is automatically redirected to the login page.
    if current_user.is_authenticated:
        return redirect(url_for('users.login'))
    form = Login() #The form is set equal to the Login class in forms.py and undergoes the login prcoess  
    if form.validate_on_submit():
        user = User.query.filter_by(email= form.email.data).first() # The user variable is set equal to the email address entered by the user.
        if user and bcrypt.check_password_hash(user.password, form.password.data): # if the email and password entered by the user is correct the user will be logged in and redirected to the main homepage.
            login_user(user, remember = form.remember.data)
            nextpage = request.args.get('next')
            return redirect(nextpage) if nextpage else redirect(url_for('main.HomePage'))
        else: # However if the email and password entered is not correct , a message will be flashed
            flash('Login Unsuccessful. Please check email and password', 'danger') # message flashed says 'Login Unsuccessful. Please check email and password'
    return render_template('login.html', title='Login', form=form) # This renders the HTML Template , the template name is 'login.html', variables being passed - title='Login', form=form


@users.route("/logout")# This links the URL /logout to this subroutine 
def logout():
    logout_user() # This logs the user out of their account 
    return redirect(url_for('main.HomePage')) # This redirects the logged out user to the homepage 


@users.route("/account",methods=['GET', 'POST']) # This links the URL of the account Page to this subroutine . The html methods being used are GET & POST
@login_required # This page can only be accessed when the user has logged in
def account():
    form = UpdateAccount()#The form is set equal to the UpdateAccount class in forms.py and undergoes the update account prcoess  
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_pic(form.picture.data) # The variable picture_file is set equal to the picture 
            current_user.image_file = picture_file # The current profile picture of the user is now set equal to the picture chosen by the user 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username # The new username entered by the user in the form is set equal to the current username of the user. This changes the username of the user's account
        form.email.data = current_user.email # The new email entered by the user in the form is set equal to the current email address of the user. This changes the email address of the user's account
    image_file = url_for('static', filename= 'webby_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', 
        image_file = image_file, form = form) # This renders the HTML Template , the template name is 'account.html', variables being passed - title='Account', image_file = image_file, form = form

@users.route('/user/<string:username>')  # This links the URL of the user's profile page to this subroutine . 
def user_post(username):
    page = request.args.get('page', 1, type = int)
    user = User.query.filter_by(username = username).first_or_404()#Gets First User with Username and if user does not exist , a page 404 is returned 
    posts = Post.query.filter_by(author= user).order_by(Post.date_posted.desc()).paginate(page = page, per_page = 5 ) #Allows Posts to Be Posted on users profile page
    return render_template("user_post.html", posts = posts, user = user) # This renders the HTML Template , the template name is 'user_post.html', variables being passed - posts = posts, user = user

@users.route("/reset_password", methods = ['GET', 'POST'])  # This links the URL of the reset password page to this subroutine . The html methods being used are GET & POST
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.HomePage')) #If the current user is already logged in to an account the user will be redirected to the homepage
    form = RequestReset() #The form is set equal to the RequestReset class in forms.py and undergoes the request reset password prcoess  
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first() # The user variable is set equal to the email address entered by the user.
        send_email(user) #An email is sent to the email adress of the user entered in the form 
        flash('An email has been sent to reset your password', 'info') # Message displayed to user saying email has been sent succesfully
        return redirect(url_for('users.login'))
    return render_template("reset_request.html", title = "Reset Password", form = form)


#This function is linked to the resetting the password of the account 
@users.route("/reset_password/<token>", methods = ['GET', 'POST'])
def reset_tpassword(token): # the subroutine takes the argument token . The token is the link which is sent to the email address of the account. The token is set to expire in 60 minutes 
    if current_user.is_authenticated:
        return redirect(url_for('main.HomePage'))
    user = User.verify_reset_token(token) #This verifies that the user that clicked on the link sent is the correct account & email addrss   
    if not user:
        flash('That is an invalid or expired token', 'warning') #If token has expired after 1 hour or if the token is not linked to that emaiL, this text will pop up
        return redirect(url_for('users.reset_request'))
    form = ResetPassword() # variable form set equal to the class ResetPassword in forms.py 
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf- 8') # Hash function applied to new password entered by user
        user.password = hashed_password # Old password replaced by new password
        db.session.commit()
        flash('Your password has been changed! You are now able to log in', 'success')
        return redirect(url_for('users.login')) # User redirected to login page 
    return render_template("reset_tpassword.html", title = "Reset Password", form = form) 


@users.route('/follow/<string:username>')
def follow(username): # username is taken as argument in function
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.') # If user doesn't exist or there is an error, this message is popped up
        return redirect(url_for('main.HomePage'))

templates/About.html

{% extends "layout.html" %}
{% block content %}

<article class="media content-section">
<div align="center">
<div>
<h1>Welcome to TheScholarSpace </h1> 
</div>

<div>
<h2> What is TheScholarSpace about? </h2>
</div>

<div>
<p> This is an educational social media website designed for A-level students who are undergoing their a levels currently.</p>

<img src="https://www.cam.ac.uk/sites/www.cam.ac.uk/files/styles/content-580x288/public/news/news/sutton1top.jpg?itok=r9FAIifv" >



</div>

<p> On this website , Students will be able to communicate with each other, share their tips and advice. <p>

<p>At TheScholarSpace, we know the best support for students often comes from other students - the people who are facing exactly the same challenges as you or who have just managed to overcome them.

TheScholarSpace is a student community that exists for every student to use to support each other – whatever your background. For A levels and everything else life decides to throw at you.
TheScholarSpace community is here for you. </p>

</div>
</article>

{% endblock content %}


templates/HomePage.html
{% extends "layout.html" %}
{% block content %}

<article class="media content-section">
<div align="center">
<div>

<h1>Welcome to TheScholarSpace </h1> 

{% if current_user.is_authenticated %}


   <img  src = "{{ url_for('static', filename = 'webby_pics/' + current_user.image_file)}}" height="200" width="200">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
      <p class="uk-margin-remove">{{ current_user.followers.count() }} followers, {{ current_user.followed.count() }} following.</p>


      <a class="mr-2" href="{{ url_for('users.user_post', username=current_user.username) }}">Check out Profile Page</a>

<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li{% if not show_followed %} class="active"{% endif %}><a href="{{ url_for('main.show_all') }}">All | </a></li>
        <li{% if show_followed %} class="active"{% endif %}><a href="{{ url_for('main.show_followed') }}"> Following</a></li>
    </ul>
    {% for post in posts %}
        <article class="media content-section">
            <div class="article-metadata">
              <div>
                <img class = "rounded-circle article-img" src = "{{ url_for('static', filename = 'webby_pics/' + post.author.image_file)}}">
              <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          </div>
        </article>
    {% endfor %}</div>
	{% else %}
	<small class="text-muted">
            Sign Up to access Account hub ? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up</a>
	{% endif %}
	


	
{% endblock content %}

templates/comments_post.html

{% extends "layout.html" %}
{% block content %}
{% import 'bootstrap/wtf.html' as wtf %}

  <article class="media content-section">
  <img class = "rounded-circle article-img" src = "{{ url_for('static', filename = 'webby_pics/' + post.author.image_file)}}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
      <!-- This outputs the username of the post -->
      <small class="text-muted">{{ post.date_posted.strftime('%a-%d-%m-%Y') }}</small>
      <!-- https://docs.python.org/2/library/time.html -->

       

      {% if post.author == current_user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.edit_post', post_id=post.id) }}">Edit</a>

            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            
            
          </div>
      {% endif %}


    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>



    <div>

      {{ post.likes.count() }} likes

    </div>



    <div>

    {% if current_user.has_liked_post(post) %}
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('posts.like_action', post_id=post.id, action='unlike') }}">Unlike</a>
    {% else %}
    <a class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}"><span class="glyphicon glyphicon-thumbs-up"></span> Like</a>

    {% endif %}
</div>
    
  

<a href="{{ url_for('posts.post', post_id=post.id) }}#comments">
  <span class="label label-primary">{{ post.comments.count() }} Comments</span>
  </a>





  {% include 'comments.html' %}


  {% if current_user.is_authenticated %}


  <div class="comment-form">
    {{ wtf.quick_form(form) }}
  </div>

  {% else %}

  <a href="{{url_for('users.signup')}}"> If you want to comment and dont have an account , Signup?</a>

  {% endif %}

  </div>
</article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
  




templates/compscipost.html
{% extends "layout.html" %}
{% block content %}
	
  {% if current_user.is_authenticated %}

	{% for post in posts.items %}
	<article class="media content-section">
  <img class = "rounded-circle article-img" src = "{{ url_for('static', filename = 'webby_pics/' + post.author.image_file)}}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
      <!-- This outputs the username of the post -->
      <small class="text-muted">{{ post.date_posted.strftime('%a-%d-%m-%Y') }}</small>
      <!-- https://docs.python.org/2/library/time.html -->
    </div>
    <h2><a class="article-title" href="{{url_for('posts.post', post_id = post.id)}}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
	{%endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{url_for('main.compscipost', page = page_num)}}">{{page_num}}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{url_for('main.compscipost', page = page_num)}}">{{page_num}}</a>

    {% endif %}

  {% else %}


  {% endif %}


  {%endfor %}

  {% else %}
  <small class="text-muted">
            Sign Up to access Post Area <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up</a>
  {% endif %}
{% endblock content %}

templates/followers.html
{% extends "layout.html" %}
{% block content %}


<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>Users</th></thead>
    {% for follow in follows %}
    <tr>
        <td>
            <a href="{{ url_for('users.user_post', username = follow.user.username) }}">
                {{ follow.user.username}}
            </a>
        </td>
    </tr>
    {% endfor %}
    </table>

    
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type = "text/css" href="{{url_for('static', filename = 'main.css') }}">


     {% if title %}
    	<title> TheScholarSpace - {{title}}</title>
    {% else %}
    	<title> TheScholarSpace </title>
    {% endif %}

    
</head>
<body>
	<header class="site-header">


    
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">TheScholarSpace</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{{ url_for('main.HomePage') }}">Home</a>
          
          <a class="nav-item nav-link" href="{{ url_for('main.compscipost')}}">Blog</a>
          <a class="nav-item nav-link" href="{{ url_for('main.pastpaper')}}"> Past Papers </a>
          <a class="nav-item nav-link" href="{{ url_for('main.about')}}"> About </a>

        

        </div>

        {% if g.search_form %}
          <form class="form-inline my-2 my-lg-0" method = "get" action="{{ url_for('main.search') }}">
            <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
                    
            
            </div>
           </form>
                
          {% endif %}
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}


          <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post </a>
          <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>

          <a class="nav-item nav-link" href="{{ url_for('users.messages') }}">Messages
          {% set new_messages = current_user.new_messages() %}
          <span id="message_count" class="badge"
          style="visibility: {% if new_messages %}visible
          {% else %}hidden {% endif %};">{{ new_messages }}
          </span>
          </a>

          {% block scripts %}
        <script>
          // ...
        function set_message_count(n) {
          $('#message_count').text(n);
          $('#message_count').css('visibility', n ? 'visible' : 'hidden');
        }
        </script>
        
        <script>
        {% if current_user.is_authenticated %}
        $(function() {
            var since = 0;
            setInterval(function() {
                $.ajax('{{ url_for('users.notifications') }}?since=' + since).done(
                    function(notifications) {
                        for (var i = 0; i < notifications.length; i++) {
                            if (notifications[i].name == 'unread_message_count')
                                set_message_count(notifications[i].data);
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 10000);
        });
        {% endif %}
      </script>
        {% endblock %}
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
          <a class="nav-item nav-link" href="{{ url_for('users.signup') }}">SignUp</a>

        


          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

	<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
    	{% with messages = get_flashed_messages(with_categories = true) %}

    	{% if messages %}

    	{% for category,message in messages %}

    	<div class="alert alert- {{category}}">
    		{{ message }}
    		


    	</div>

    	{% endfor %}

    	{% endif %}

    	{% endwith %}
      {% block content %}{% endblock %}
    
    </div>
</main>


<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>